### ISSUE TITLE
Data type of document's characteristics

### ISSUE THREAD

**Issue by TCMiranda** [73rhodes/dclassify#4]
Hey,
What types of data are supported on document's characteristics
Does the type alter the result of the training?

ex. How would and Number "age" be treated as a characteristic? 
Will 29 and 31 be close compared to 29 and 20?

Thanks!

**Comment by 73rhodes** [comment]
A document is really a collection of tokens. Tokens are usually strings, but they could be data type. It's important to understand that the tokens are not compared. Rather, statistics are generated based on the token being present or absent from a document. If you wanted to do binary classification based on age, you would probably create a string token like "age 29" or "age range [21 - 30]", add this string token to the document, and use it along with other details to perform training and classification.
