### ISSUE TITLE
Backup/store the trained logic

### ISSUE THREAD

**Issue by guyisra** [73rhodes/dclassify#5]
Is it possible to store the classifiers knowledge in a file or DB (not just in memory)?

**Comment by 73rhodes** [comment]
Sure, but that functionality belongs in the code which uses this library. Once you've created and trained a classifier, simply convert it to a JSON string and store that however you want. To recreate the trained classifier, parse the string into an object and set it's prototype to be the `Classifier` prototype.

```javascript
var Classifier = dclassify.Classifier;
var classifierJson = JSON.stringify(classifier1);
// use node's filesystem API or write to a database

// later on, recreate the trained classifier
var classifier2 = JSON.parsr(classifierJson);
Object.setPrototypeOf(classifier2, Classifier);
```

**Comment by niftylettuce** [comment]
FYI it can just be:

```js
const classifier = require('./classifier.json');
Object.setPrototypeOf(classifier, new Classifier());
```

Note you are missing the "new Classifier()" in the `setPrototypeOf`.

**Comment by 73rhodes** [comment]
Thanks, updated the example; the `getPrototypeOf` call is needed as well.
